version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "11:00"
  open-pull-requests-limit: 99
  versioning-strategy: increase
  ignore:
  - dependency-name: webpack
    versions:
    - 5.17.0
    - 5.19.0
    - 5.21.1
    - 5.21.2
    - 5.24.2
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.3
    - 2.32.8
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.2.2
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: react-map-gl
    versions:
    - 6.0.3
    - 6.1.1
    - 6.1.4
    - 6.1.7
  - dependency-name: gatsby-plugin-offline
    versions:
    - 3.10.0
    - 3.9.0
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.1
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 2.13.1
    - 2.13.4
  - dependency-name: gatsby-transformer-json
    versions:
    - 2.10.0
  - dependency-name: gatsby-plugin-feed
    versions:
    - 2.12.0
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 2.11.0
  - dependency-name: gatsby-plugin-sitemap
    versions:
    - 2.11.0
  - dependency-name: gatsby-transformer-remark
    versions:
    - 2.15.0
  - dependency-name: gatsby-remark-images
    versions:
    - 3.10.0
  - dependency-name: gatsby-remark-autolink-headers
    versions:
    - 2.10.0
  - dependency-name: gatsby-plugin-netlify
    versions:
    - 2.10.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.9.0
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 2.11.0
  - dependency-name: gatsby-transformer-yaml
    versions:
    - 2.10.0
  - dependency-name: gatsby-remark-responsive-iframe
    versions:
    - 2.10.0
  - dependency-name: gatsby-remark-smartypants
    versions:
    - 2.9.0
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.10.0
  - dependency-name: gatsby-image
    versions:
    - 2.10.0
