title: Dan Palmer
email: contact@danpalmer.me
description: >
  I'm a software developer at Thread in London, and a University of Southampton
  alumni where I studied Computer Science, specialising in Mobile and Secure
  Systems.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://danpalmer.me" # the base hostname & protocol for your site

# Social
githubUsername: danpalmer
twitterUsername: danpalmer

# Build settings
markdown: kramdown

themeColor: grey # green, blue, orange, purple, grey
fixedNav: 'true' # true or false

permalink: /:year/:month/:title
markdown: kramdown
include: [_pages]
exclude: [_site, README.md]
sass:
  style: compressed
