baseURL = 'https://danpalmer.me/'
languageCode = 'en-gb'
title = 'Dan Palmer'
timeZone = 'Europe/London'
enableRobotsTXT = true
enableGitInfo = true
disableKinds = ["taxonomy", "term", "section"]

[permalinks]
  posts = '/:slugorcontentbasename'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'github'
    tabWidth = 2
    noClasses = false

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "rss"
