[build]
    command = "yarn run ci"
    publish = "public"

[build.processing.css]
    bundle = true
    minify = true

[build.processing.js]
    bundle = true
    minify = true

[build.processing.html]
    pretty_urls = false

[build.processing.images]
    compress = false

[[redirects]]
    from = "/.well-known/webfinger"
    to = "https://social.danpalmer.me/.well-known/webfinger"
    status = 301
    force = true

[[redirects]]
    from = "/.well-known/nodeinfo"
    to = "https://social.danpalmer.me/.well-known/nodeinfo"
    status = 301
    force = true
