name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1.4.1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn run check
      - name: Build
        run: yarn run build
      - name: Test
        run: yarn run test
      - name: Move build
        run: mv public build
      - name: Deploy
        uses: danachim/gh-action-deploy-netlify@v1
        with:
          AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          DEPLOY_PROD: "true"
