name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1.4.1
        with:
          node-version: 12.x

      - name: Configure yarn cache
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules/
          key: yarn-1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-

      - name: Install dependencies
        run: yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'

      - name: Lint
        run: yarn run check
      - name: Build
        run: yarn run build
      - name: Test
        run: yarn run test

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.0.11
        with:
          publish-dir: ./public
          production-branch: master
          deploy-message: Deploy from GitHub Actions
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
