name: Deploy

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Configure yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: node_modules/
          key: yarn-1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-

      - name: Install dependencies
        run: yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'

      - name: Lint
        run: yarn run check

      - name: Build
        run: yarn run build

      - name: Test
        run: yarn run test

      - name: Upload
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "public/**/*"
          target: "/config/sites/danpalmer.me/"
