name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1.4.1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn run check
      - name: Build
        run: yarn run build
      - name: Test
        run: yarn run test
      - uses: jsmrcaga/action-netlify-deploy@v1.0.1
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: public
