name: Nike Sync

on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run sync script
        run: |
          python scripts/nike_sync.py ${{ secrets.NIKE_ACCESS_TOKEN }}
      - name: Commit new runs
        run: |
          if git diff-index --quiet HEAD --; then
            echo "No new runs, finishing"
          else
            git add data/activities/*
            git commit -m "Auto committing new runs"
            git push
          fi
          
