name: Test

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.154.5"
          extended: true

      - name: Build
        run: hugo --minify

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Test
        run: node test.js
